services:
  pgdatabase:
    container_name: pgdatabase-test
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_hw_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin-test
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"